<a href="https://colab.research.google.com/github/U-ohata/Rabbit_Report_2/blob/Rabbit_Report_Colaboratory/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

線形回帰モデル

In [1]:
#numpyと、ボストンの住宅データセット読み込み
import numpy as np
from sklearn.datasets import load_boston
from pandas import DataFrame

In [2]:
#boston変数にデータ読み込み
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [3]:
#bostonデータ表示
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [4]:
#目的変数表示
print(boston['target'])

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [5]:
#説明変数表示
print(boston['data'])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [6]:
#bostonデータをデータフレームに変換
df = DataFrame(data=boston.data, columns = boston.feature_names)

In [7]:
#データフレーム表示
df.head(30)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0   0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1   0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2   0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3   0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4   0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
5   0.02985   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.12   5.21
6   0.08829  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  395.60  12.43
7   0.14455  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  19.15
8   0.21124  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.63  29.93
9   0.17004  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.71  17.10
10  0.22489  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  392.52  20.45
11  0.11747  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  13.27
12  0.09378  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  390.50  15.71
13  0.62976   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  396.90   8.26
14  0.63796   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  380.02  10.26
15  0.62739   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  395.62   8.47
16  1.05393   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  386.85   6.58
17  0.78420   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  386.75  14.67
18  0.80271   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  288.99  11.69
19  0.72580   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  390.95  11.28
20  1.25179   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.57  21.02
21  0.85204   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  392.53  13.83
22  1.23247   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  396.90  18.72
23  0.98843   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  394.54  19.88
24  0.75026   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  394.33  16.30
25  0.84054   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  303.42  16.51
26  0.67191   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.88  14.81
27  0.95577   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  306.38  17.28
28  0.77299   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  387.94  12.80
29  1.00245   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  380.23  11.98

[30 rows x 13 columns]

In [8]:
#データフレームに価格を追加
df['PRICE']=np.array(boston.target)

In [9]:
#データフレーム再度表示(PRICE追加)
df.head(30)

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0   0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1   0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2   0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3   0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4   0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2
5   0.02985   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.12   5.21   28.7
6   0.08829  12.5   7.87   0.0  0.524  ...  311.0     15.2  395.60  12.43   22.9
7   0.14455  12.5   7.87   0.0  0.524  ...  311.0     15.2  396.90  19.15   27.1
8   0.21124  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.63  29.93   16.5
9   0.17004  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.71  17.10   18.9
10  0.22489  12.5   7.87   0.0  0.524  ...  311.0     15.2  392.52  20.45   15.0
11  0.11747  12.5   7.87   0.0  0.524  ...  311.0     15.2  396.90  13.27   18.9
12  0.09378  12.5   7.87   0.0  0.524  ...  311.0     15.2  390.50  15.71   21.7
13  0.62976   0.0   8.14   0.0  0.538  ...  307.0     21.0  396.90   8.26   20.4
14  0.63796   0.0   8.14   0.0  0.538  ...  307.0     21.0  380.02  10.26   18.2
15  0.62739   0.0   8.14   0.0  0.538  ...  307.0     21.0  395.62   8.47   19.9
16  1.05393   0.0   8.14   0.0  0.538  ...  307.0     21.0  386.85   6.58   23.1
17  0.78420   0.0   8.14   0.0  0.538  ...  307.0     21.0  386.75  14.67   17.5
18  0.80271   0.0   8.14   0.0  0.538  ...  307.0     21.0  288.99  11.69   20.2
19  0.72580   0.0   8.14   0.0  0.538  ...  307.0     21.0  390.95  11.28   18.2
20  1.25179   0.0   8.14   0.0  0.538  ...  307.0     21.0  376.57  21.02   13.6
21  0.85204   0.0   8.14   0.0  0.538  ...  307.0     21.0  392.53  13.83   19.6
22  1.23247   0.0   8.14   0.0  0.538  ...  307.0     21.0  396.90  18.72   15.2
23  0.98843   0.0   8.14   0.0  0.538  ...  307.0     21.0  394.54  19.88   14.5
24  0.75026   0.0   8.14   0.0  0.538  ...  307.0     21.0  394.33  16.30   15.6
25  0.84054   0.0   8.14   0.0  0.538  ...  307.0     21.0  303.42  16.51   13.9
26  0.67191   0.0   8.14   0.0  0.538  ...  307.0     21.0  376.88  14.81   16.6
27  0.95577   0.0   8.14   0.0  0.538  ...  307.0     21.0  306.38  17.28   14.8
28  0.77299   0.0   8.14   0.0  0.538  ...  307.0     21.0  387.94  12.80   18.4
29  1.00245   0.0   8.14   0.0  0.538  ...  307.0     21.0  380.23  11.98   21.0

[30 rows x 14 columns]

In [10]:
#RM列のみdataに抽出
data = df.loc[:, ['RM']].values

In [11]:
#RM列のみ表示
data[0:30]

array([[6.575],
       [6.421],
       [7.185],
       [6.998],
       [7.147],
       [6.43 ],
       [6.012],
       [6.172],
       [5.631],
       [6.004],
       [6.377],
       [6.009],
       [5.889],
       [5.949],
       [6.096],
       [5.834],
       [5.935],
       [5.99 ],
       [5.456],
       [5.727],
       [5.57 ],
       [5.965],
       [6.142],
       [5.813],
       [5.924],
       [5.599],
       [5.813],
       [6.047],
       [6.495],
       [6.674]])

In [12]:
#価格のみ抽出、表示
target = df.loc[:, 'PRICE'].values
target[0:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

In [13]:
#線形回帰モデルインポート
from sklearn.linear_model import LinearRegression

In [14]:
#model変数に線形回帰モデル代入、
model = LinearRegression()
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [15]:
#モデルに学習用データを充てる
model.fit(data,target)

LinearRegression()

In [18]:
#実際の予測(RM入力、価格出力)
model.predict([[10]])

array([56.35046904])

In [19]:
#CRIMとRMのみ抽出し、target2に価格抽出
data2 = df.loc[:, ['CRIM','RM']].values
target2 = df.loc[:, 'PRICE'].values

In [20]:
#data2の中身を5つ表示
print(data2[0:5])

[[6.320e-03 6.575e+00]
 [2.731e-02 6.421e+00]
 [2.729e-02 7.185e+00]
 [3.237e-02 6.998e+00]
 [6.905e-02 7.147e+00]]


In [21]:
#model2に線形回帰モデルを充てて、学習
model2 = LinearRegression()
model2.fit(data2,target2)

LinearRegression()

In [22]:
#CRIMとRMを代入して出力
model2.predict([[0.6,7]])

array([29.33381032])